move_bindings:
  forward_left: u
  forward: i
  forward_right: o
  backward_left: m
  backward: ','
  backward_right: '.'
  left: j
  no_movement: k
  right: l
  up: t
  down: b

holonomic_move_bindings:
  holonomic_forward: I
  holonomic_backward: '<'
  holonomic_left: J
  holonomic_right: L
  holonomic_forward_left: U
  holonomic_forward_right: O
  holonomic_backward_left: M
  holonomic_backward_right: '>'
  holonomic_no_movement: K

speed_bindings:
  increase_max_speed_by_10: q
  decrease_max_speed_by_10: z
  decrease_linear_speed_by_10: x
  increase_linear_speed_by_10: w
  decrease_angular_speed_by_10: c
  increase_angular_speed_by_10: e

custom_bindings:
  # Format: string name of topic to publish to: key press
  publish:
    mission_start: s
    mission_stop: p
    waypoint_capture_start: w
    target_capture_start: t
    scene_scan_start: a
  subscribe:
    # Example: subscribe_topic: /some/topic
