move_bindings:
  forward_left: u
  forward: i
  forward_right: o
  backward_left: m
  backward: ','
  backward_right: '.'
  left: j
  no_movement: k
  right: l
  up: t
  down: b

holonomic_move_bindings:
  holonomic_forward: I
  holonomic_backward: '<'
  holonomic_left: J
  holonomic_right: L
  holonomic_forward_left: U
  holonomic_forward_right: O
  holonomic_backward_left: M
  holonomic_backward_right: '>'
  holonomic_no_movement: K

speed_bindings:
  increase_max_speed_by_10: q
  decrease_max_speed_by_10: z
  decrease_linear_speed_by_10: x
  increase_linear_speed_by_10: w
  decrease_angular_speed_by_10: c
  increase_angular_speed_by_10: e

custom_bindings:
  custom_00:
    description: "Start mission" 
    key: "1"
    topic: /start_mission
    topic_type: std_msgs/Empty
    topic_action: publish
    data: "" 
  custom_01:
    description: "End mission" 
    key: "2"
    topic: /end_mission
    topic_type: std_msgs/Empty
    topic_action: publish
    data: ""
  custom_02:
    description: "Capture waypoint" 
    key: "3"
    topic: /capture_waypoint
    topic_type: std_msgs/Empty
    topic_action: publish
    data: ""
  custom_03:
    description: "Capture target image"
    key: "4" 
    topic: /capture_target_image
    topic_type: std_msgs/Empty
    topic_action: publish
    data: ""
  custom_04:
    description: "Start panoramic scan"
    key: "5"
    topic: /start_panoramic_scan
    topic_type: std_msgs/Empty
    topic_action: publish
    data: ""